### ISSUE TITLE
Sitemap creation WP_Query optimisation

### ISSUE THREAD

**Issue by david-binda** [Automattic/msm-sitemap#117]
In vast majority of cases, the post metas are not necessary for collecting information for the sitemap. Thus we probably could gain some precious performance improvements by specifying `'update_post_meta_cache' => false` in https://github.com/Automattic/msm-sitemap/blob/master/msm-sitemap.php#L408

**Comment by kraftbj** [comment]
This would be rendered moot by #129. I suggest pursuing that PR.
