### ISSUE TITLE
Disable JP's Publicize for Sitemap post status by default

### ISSUE THREAD

**Issue by david-binda** [Automattic/msm-sitemap#118]
We have noticed that JP's Publicize is creating a new post meta for every sitemaps's post. Adding following filter somewhere should fix that:

```
        add_filter( 'publicize_should_publicize_published_post', function( $publicize, $post ) {
            if ( Metro_Sitemap::SITEMAP_CPT === $post->post_type ) {
                $publicize = false;
            }
            return $publicize;
        }, 10, 2 );
```

**Comment by kraftbj** [comment]
This is caused by an issue in Jetpack solved by the above PR. Jetpack's Publicize module hooks into the post transition to adds meta on all publishing posts without confirming the post type is Publicize-able.

**Comment by kraftbj** [comment]
The resolution for this is shipping in Jetpack 6.1, due out w/i the next 24 hours.
