### ISSUE TITLE
Do not attempt to generate posts for non-existing dates

### ISSUE THREAD

**Issue by david-binda** [Automattic/msm-sitemap#133]
When using the WP CLI generation, you can notice following:

```
Generating sitemap for 2017-2-28
Generating sitemap for 2017-2-29
Generating sitemap for 2017-2-30
Generating sitemap for 2017-2-31
```

There is no such a date as Feb. 30th nor Feb 31th.

Likely originating here: https://github.com/Automattic/msm-sitemap/blob/547eadc1c159e23825690a3abde27fbea70b217c/includes/wp-cli.php#L102

**Comment by GaryJones** [comment]
While #136 had an initial fix, https://github.com/Automattic/msm-sitemap/pull/130/ has a more comprehensive fix that doesn't fall back to a value of 31 days.
