### ISSUE TITLE
Limit sitemap date range

### ISSUE THREAD

**Issue by kasparsd** [Automattic/msm-sitemap#146]
We would like to exclude all posts created before 2015 from the generated sitemap. 

Currently there is the `msm_sitemap_skip_post` filter to exclude individual posts from the sitemap, however, there is no way to filter the output of `build_root_sitemap_xml()`.

**Comment by lgedeon** [comment]
Relates to XWP-1367

**Comment by lgedeon** [comment]
PR #147 has now been approved how do we go about merging and then deploying the VIP?

**Comment by GaryJones** [comment]
It's on my backlog to do a new release and a deploy to VIP.

**Comment by GaryJones** [comment]
Noting that this was released as [1.4.1](https://github.com/Automattic/msm-sitemap/releases/tag/1.4.1).
