### ISSUE TITLE
Allow custom modified posts query

### ISSUE THREAD

**Issue by emrikol** [Automattic/msm-sitemap#155]
Some sites may have different criteria for what is considered a "modified" post, so we should add a filter to override `Metro_Sitemap::get_last_modified_posts()`, specifically here:

https://github.com/Automattic/msm-sitemap/blob/fa4fff265d435b6185f1d1a0dc803b9b5ff52e4e/msm-sitemap.php#L590

**Comment by rbcorrales** [comment]
A new `msm_pre_get_last_modified_posts` filter was added for this in https://github.com/Automattic/msm-sitemap/pull/178.
