### ISSUE TITLE
News Sitemap

### ISSUE THREAD

**Issue by mjangda** [Automattic/msm-sitemap#5]
Maybe we should support News Sitemaps too!

**Comment by nitinchaudhry** [comment]
How we can change the Language attribute from news-sitemap.xml ,i have tried both 

add_filter('language_attributes', 'custom_lang_attr');
function custom_lang_attr() {
  return 'lang="ml-IN"';
}

and $item['news:news']['news:publication']['news:language'] ='ml';

**Comment by mjangda** [comment]
Not a good fit for this plugin since the requirements for News Sitemaps are very different.
