### ISSUE TITLE
Large Sitemap List Issue

### ISSUE THREAD

**Issue by ericmann** [Automattic/msm-sitemap#51]
If you're using Google Webmaster Tools, you're limited to viewing only 400 sitemaps in the UI.  With sitemaps being generated _daily_ with this plugin, that means we're limited to just over a year's worth of sitemaps in the Google UI.

Monthly sitemaps (instead of daily sitemaps) should be an option.

**Comment by pkevan** [comment]
This has caused us issues debugging our sitemaps in webmaster tools as we currently have over 4k sitemap dates.

Although this is a UI issue it's something which is fixable

**Comment by philipjohn** [comment]
Fixed by #119
