### ISSUE TITLE
Incorrect Lastmod date

### ISSUE THREAD

**Issue by donohoe** [Automattic/msm-sitemap#66]
<lastmod>  should be the date of last modification of the file - not necessarily the date the file was created

![image](https://cloud.githubusercontent.com/assets/36363/3735883/b58e42b8-1728-11e4-981c-46fae7ffaca4.png)

which leads to this in Webmaster tools:

![image](https://cloud.githubusercontent.com/assets/36363/3736363/0a94f71c-172d-11e4-91b6-859b98942820.png)

(I'm digging in to make sure this isn't a quick of our setup... but so far doesn't seem so)

http://www.sitemaps.org/protocol.html

**Comment by mdbitz** [comment]
@mjangda > This looks like it can be closed out. `get_post_modified_time` is used for the lastmod field and latest code uses the date format 'c' which won't show as invalid date in Webmaster tools.
