### ISSUE TITLE
lastmod for index

### ISSUE THREAD

**Issue by markparolisi** [Automattic/msm-sitemap#68]
The `lastmod` node is missing in the sitemap index.

https://support.google.com/webmasters/answer/71453?hl=en&ref_topic=4581190

**Comment by mdbitz** [comment]
@mjangda > This looks like it can be closed out. The unit test `test_sitemap_posts_were_created` verifies that lastmod is set and expected value.

**Comment by mjangda** [comment]
@mdbitz This issue is actually proposing adding a `lastmod` to each sub-sitemap entry in the root sitemap (i.e. `/sitemap.xml`) which we don't currently do.
