### ISSUE TITLE
Add method to delete a sitemap by date

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/msm-sitemap#69]
Need to encapsulate the logic to delete the sitemap for a given date. Currently exists like this:

```
$total_url_count -= intval( get_post_meta( $sitemap_id, 'msm_indexed_url_count', true ) );
update_option( 'msm_sitemap_indexed_url_count' , $total_url_count );
wp_delete_post( $sitemap_id, true );
do_action( 'msm_delete_sitemap_post', $sitemap_id, $year, $month, $day );
```

https://github.com/Automattic/msm-sitemap/blob/master/msm-sitemap.php#L396-401

This will come in handy to simplify the `Metro_Sitemap::generate_sitemap_for_date` function, as well as help fix #63

**Comment by mdbitz** [comment]
@mjangda This issue should be closed. Current master has `delete_sitemap_for_date` which calls `delete_sitemap_by_id` and contains the above logic to update url count
