### ISSUE TITLE
lastmod time NOT in UTC

### ISSUE THREAD

**Issue by kimcheung** [Automattic/msm-sitemap#88]
`<lastmod>2016-12-01T11:15:43Z</lastmod>`
The lastmod time is appended with 'Z' signifying it is the [ISO-8601 UTC timestamp](https://en.wikipedia.org/wiki/ISO_8601).
However, it is NOT the UTC time, but in actuality, the local time.

This can be easily fixed by modifying line [430 in msm-sitemap.php](https://github.com/Automattic/msm-sitemap/blob/master/msm-sitemap.php#L430) from 
`$url->addChild( 'lastmod', get_the_modified_date( 'Y-m-d' ) . 'T' . get_the_modified_date( 'H:i:s' ) . 'Z' );`
to
`$url->addChild( 'lastmod', get_post_modified_time( 'Y-m-dTH:i:s', true ) );`

**Comment by mjangda** [comment]
Thanks for the report @kimcheung!
