### ISSUE TITLE
Fix/Improve tests

### ISSUE THREAD

**Issue by mjangda** [Automattic/msm-sitemap#92]
The existing tests are somewhat broken:

```
..F.F                                                               5 / 5 (100%)
Time: 1.08 minutes, Memory: 36.00MB
There were 2 failures:
1) WP_Test_Sitemap_Stats::test_site_stats_creation
Failed asserting that 1 matches expected 3.
/home/travis/build/Automattic/msm-sitemap/tests/test_sitemap_stats.php:54
2) WP_Test_Sitemap_Stats::test_site_stats_for_deleted_post
Failed asserting that 3 matches expected 0.
/home/travis/build/Automattic/msm-sitemap/tests/test_sitemap_stats.php:109
```

Also, they are very slow. It might be good to look at redo-ing them to make them faster and maybe extending coverage a bit.

**Comment by mdbitz** [comment]
Ran some initial executions of the Unit Tests to determine bottlenecks and scope of tests.

**Issue 1** : MSM_SiteMap_Test->build_sitemaps 

Current logic relies on continually iterating over scheduled cron tasks to execute the msm_cron_generate_sitemap_for_* actions. This causes startup method to be ~42s (creation) and 123s (stats)

This needs to be updated to call the actions directly to minimize processing time. 

**Issue 2** :  WP_Test_Sitemap_Creation->test_sitemap_posts_were_created

Comparison of date is using string comaprison and doesn't account for formats differences
 -2016-12-29T00:00:00Z
+2016-12-29UTC00:00:000

Needs to be normalized.

**Issue 3** :  WP_Test_Sitemap_Stats->test_site_stats_for_deleted_post

Test is currently failing. The individual checks for each Post Date is validating but the overall count after all posts are deleted are not aligning.

Need to review Plugin logic to see what is occuring. Also this probably should be a separate test.

**Issue 4** : Documentation

Scope of Unit Tests need to be properly documented in comments. In some cases no documentation exists for test cases.

**Next Steps 1** : Unit Tests to test Post Status

Draft, Pending Review, Private -> ensure aren't in SiteMap

**Next Steps 2** : Unit Tests for Custom Post Type Support 

(get_supported_post_types_in)

**Next Steps 3** : Unit Tests Coverage

Individual Functions in msm-sitemap need to be reviewed to see if they are covered and have appropriate tests created.

_Log Files_

[test-exec-short-log.txt](https://github.com/Automattic/msm-sitemap/files/679408/test-exec-short-log.txt)

[test-exec-verbose-log.txt](https://github.com/Automattic/msm-sitemap/files/679409/test-exec-verbose-log.txt)

**Comment by mdbitz** [comment]
Updates on Resolution Steps

**Issue 1** : 

Resolution > Switch to calling the action for all created posts. Need to update the Helper class appropriately
MSM_Sitemap_Builder_Cron::generate_sitemap_for_year_month_day( $args );

**Issue 2** :

Resolution > fix the format in test case to match plugin

**Comment by mdbitz** [comment]
Current Status

Issues 1,2,3 are resolved. In Process of updating the documentation in the tests folder once complete will submit a push request. Enhancements will be in a second push request.

> ......                                                              6 / 6 (100%)
> 
> Time: 33.59 seconds, Memory: 40.75MB

**Comment by mdbitz** [comment]
After running a quick test before submitting the pull request, realized that their was additional issue with how the Tests were generating days for post. Updating to use php date() function so tests don't fail on the 1-3 of the month.

**Comment by mdbitz** [comment]
Note Pull Request #101 updated date format to 'c' requiring an update to the test scripts.
