### ISSUE TITLE
get_post_year_range -> doesn't handle proper range generation when no posts exist.

### ISSUE THREAD

**Issue by mdbitz** [Automattic/msm-sitemap#98]
During creation of Unit Tests it was revealed that get_post_year_range doesn't properly handle range generation when no posts exists in the db.  Low Priority as this edge case wouldn't exist in most cases as new blogs that are created have sample content and this issue wouldn't be exposed.

```
$oldest_post_date_gmt = $wpdb->get_var( "SELECT post_date FROM $wpdb->posts WHERE post_status = 'publish' ORDER BY post_date ASC LIMIT 1" );
$oldest_post_year = date( 'Y', strtotime( $oldest_post_date_gmt ) );
```

A check should be performed to confirm that a post was returned and if not $oldest_post_year should be set to the current year.

**Comment by mjangda** [comment]
Interestingly, those variable names don't match either (we query for `post_date` but the variable is named `post_date_gmt`) which might be another bug :)

**Comment by mdbitz** [comment]
`$post_date_gmt` is the name of the variable the `post_date `gets returned to so we are good on that end. Submitting a pull request that resolves this issue and passes unit tests.

-- -- -- --

```
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml

Notice: C:\tmp\wordpress-tests-lib\includes/../data/themedir1 is not readable in C:\tmp\wordpress\wp-includes\theme.php on line 471
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

...............................                                   31 / 31 (100%)

Time: 2.35 minutes, Memory: 43.50MB

OK (31 tests, 92 assertions)
```

**Comment by mdbitz** [comment]
Fix pulled into master branch. Closing.
